- name: Install Redis 7.4.1 on RHEL 8
  hosts: all
  become: true
  vars:
    redis_software_dir: "{{ software_dir }}"
    ansible_install_dir: "{{ playbook_dir }}"
  tasks:
    - name: check existing redis version 
      shell: 
        "if [[ !  -f /usr/local/bin/redis-server ]]; then echo 0;
        else if [[ $(/usr/local/bin/redis-server --version | grep 7.4.1) ]]; then echo 0;
        else echo 1; fi; fi"
      register: redis_valid
    - name: ensure existing redis version validity
      assert:
        that: redis_valid.stdout | int == 0
        fail_msg:
         - "this server is using redis version lower then 7.4.1!!!!"
         - "please upgrade before adding redis"
        quiet: yes
    - name: check existing redis instances
      find: 
        paths: /etc/redis
        patterns: '*.conf'
      register: existing_redis_confs
    - name: parse existing redis instances 
      set_fact:
        existing_ports: "{{ existing_redis_confs | json_query('files[*].path') | 
        map('regex_replace','/etc/redis/','') | map('regex_replace','.conf','') | map('int') | list }}"
    - name: used ports info
      debug: 
        msg: 
        - "these ports already used on server and will be skipped: {{ ports | intersect(existing_ports) }}"
        - "running install for ports: {{ ports | difference(existing_ports) }}"
    - name: remove existing ports from list 
      set_fact:
        ports: "{{ ports | difference(existing_ports) }}" 
    - name: calaculate used memory
      script: "{{ansible_install_dir}}/check_memory_allocation.py"
      args:
        executable: python3
      register: preused_mem
    - name: memory info 
      debug: 
        msg: 
        - "server will allocate: {{ (ports|length * memory|human_to_bytes)|human_readable }} of new memory"
        - "total server memory: {{ (ansible_memtotal_mb*1024.0*1024.0)|human_readable }}"
        - "memory already allocated in config: {{ preused_mem.stdout|trim }}"
    - name: memory check
      assert:
        that: "{{ preused_mem.stdout|trim|human_to_bytes + (ports|length * memory|human_to_bytes) }}
         <= {{ ansible_memtotal_mb*1024.0*1024.0*0.8 }}"
        fail_msg:
         - "wanted memory usage is more than 80% of server ram"
         - "please add memory or use other server"
        quiet: yes
    - name: create redis directories
      file:
        path: "{{ item.path }}"
        state: directory
        mode: 0755
        owner: root
      loop:
        - { path: /etc/redis }
        - { path: /etc/redis/clusters }
        - { path: /var/log/redis }
        - { path: /redis/data }
    - name: create data volume group
      lvg:
        vg: datavg
        pvs: /dev/sdb
    - name: create data logical volume
      lvol:
        vg: datavg
        lv: datalv
        size: +100%FREE
    - name: create data filesystem
      filesystem:
        dev: /dev/mapper/datavg-datalv
        fstype: xfs
    - name: mount data filesystem
      mount:
        path: /redis/data
        src: /dev/mapper/datavg-datalv
        fstype: xfs
        opts: defaults
        state: mounted
    - name: create individiual data directories
      file:
        path: "/redis/data/{{ port }}"
        state: directory
        mode: 0755
        owner: root
      loop: "{{ports}}"
      loop_control:
        loop_var: port
    - name: copy redis 7.4.1 binaries to server
      copy:
        src: "{{ item.path }}"
        dest: /usr/local/sbin/
        force: no
        mode: 0755
      loop:
        - { path: "{{ redis_software_dir }}/bin/redis-server" }
        - { path: "{{ redis_software_dir }}/bin/redis-sentinel" }
        - { path: "{{ redis_software_dir }}/bin/redis-server" }
        - { path: "{{ redis_software_dir }}/bin/redis-cli" }
        - { path: "{{ redis_software_dir }}/bin/redis-check-rdb" }
        - { path: "{{ redis_software_dir }}/bin/redis-check-aof" }
        - { path: "{{ redis_software_dir }}/bin/redis-benchmark" }
    - name: copy redis stack libraries to server
      copy:
        src: "{{ item.path }}"
        dest: /usr/local/lib/
        force: no
        mode: 0755
      loop:
        - { path: "{{ redis_software_dir }}/lib/rejson.so" }
        - { path: "{{ redis_software_dir }}/lib/redistimeseries.so" }
        - { path: "{{ redis_software_dir }}/lib/redisgears.so" }
        - { path: "{{ redis_software_dir }}/lib/redisearch.so" }
        - { path: "{{ redis_software_dir }}/lib/rediscompat.so" }
        - { path: "{{ redis_software_dir }}/lib/redisbloom.so" }
        - { path: "{{ redis_software_dir }}/lib/libredisgears_v8_plugin.so" }
    - name: set vm.overcommit_memory = 1 for persistence
      sysctl:
        name: vm.overcommit_memory
        value: '1'
    - name: create redis config files 
      template:
        src: "{{ansible_install_dir}}/redis_conf_template.j2"
        dest: "/etc/redis/{{port}}.conf"
        force: no
        #backup: yes
      loop: "{{ports}}"
      loop_control:
        loop_var: port
    - name: create redis service files
      template:
        src: "{{ansible_install_dir}}/redis_service_template.j2"
        dest: "/usr/lib/systemd/system/redis_{{port}}.service"
      loop: "{{ports}}"
      loop_control:
        loop_var: port
    - name: start and enable redis services
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: redis_{{port}}
      loop: "{{ports}}"
      loop_control:
        loop_var: port
